# Machine Learning - Supervised Learning  Algorithm
# 01) Linear Regression
# a) Simple Linear Regression
##### Genarely we don't import entire library/package just essential module we need, libry.module---> class

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

##### Importing CSV file

In [4]:
data1 = pd.read_csv("Boston.csv")
data1.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

##### Let take " medv " as responce variable (y) others are x variables.

##### before going to multiple linear regression let we do simple linear regression

## Model Fitting

### Creating x and y variables

In [6]:
x = data1.iloc[:,5].values.reshape(506,1)   # Called as data series, value are in  array type,  
y = data1.iloc[:,12].values                 # Check by using print(x) and print(y)

##### To fit the model we must have x as two dimentional array, that is one column and 506 rows(chek using "data.shape")  ,  Then we " Reshape " it as an array.
##### y is ok in one diamentional form

In [7]:
print("Shape of data set   :",data1.shape)   # How many columns and rows in this data set
print("Shape of single x   :",data1.iloc[:,5].values.shape)   #x single ---> One diamentional array
print("Shape of reshaped x :",data1.iloc[:,5].values.reshape(506,1).shape)   #x new --- >Now two diamentional array
print("Shape of multiple x :",data1.iloc[:,:12].values.shape)  #x multiple ---> Already Two diamentional array
print("Shape of y          :",data1.iloc[:,12].values.shape)   #y ---> OK

Shape of data set   : (506, 13)
Shape of single x   : (506,)
Shape of reshaped x : (506, 1)
Shape of multiple x : (506, 12)
Shape of y          : (506,)


### Reshaping a array

In [22]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [23]:
a = np.array([1,2,3,4,5,6,7,8,9,0]).reshape(5,2)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [24]:
a = np.array([1,2,3,4,5,6]).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

### Now x is in two diamentional array---> column metix

In [9]:
print(x)

[[ 65.2]
 [ 78.9]
 [ 61.1]
 [ 45.8]
 [ 54.2]
 [ 58.7]
 [ 66.6]
 [ 96.1]
 [100. ]
 [ 85.9]
 [ 94.3]
 [ 82.9]
 [ 39. ]
 [ 61.8]
 [ 84.5]
 [ 56.5]
 [ 29.3]
 [ 81.7]
 [ 36.6]
 [ 69.5]
 [ 98.1]
 [ 89.2]
 [ 91.7]
 [100. ]
 [ 94.1]
 [ 85.7]
 [ 90.3]
 [ 88.8]
 [ 94.4]
 [ 87.3]
 [ 94.1]
 [100. ]
 [ 82. ]
 [ 95. ]
 [ 96.9]
 [ 68.2]
 [ 61.4]
 [ 41.5]
 [ 30.2]
 [ 21.8]
 [ 15.8]
 [  2.9]
 [  6.6]
 [  6.5]
 [ 40. ]
 [ 33.8]
 [ 33.3]
 [ 85.5]
 [ 95.3]
 [ 62. ]
 [ 45.7]
 [ 63. ]
 [ 21.1]
 [ 21.4]
 [ 47.6]
 [ 21.9]
 [ 35.7]
 [ 40.5]
 [ 29.2]
 [ 47.2]
 [ 66.2]
 [ 93.4]
 [ 67.8]
 [ 43.4]
 [ 59.5]
 [ 17.8]
 [ 31.1]
 [ 21.4]
 [ 36.8]
 [ 33. ]
 [  6.6]
 [ 17.5]
 [  7.8]
 [  6.2]
 [  6. ]
 [ 45. ]
 [ 74.5]
 [ 45.8]
 [ 53.7]
 [ 36.6]
 [ 33.5]
 [ 70.4]
 [ 32.2]
 [ 46.7]
 [ 48. ]
 [ 56.1]
 [ 45.1]
 [ 56.8]
 [ 86.3]
 [ 63.1]
 [ 66.1]
 [ 73.9]
 [ 53.6]
 [ 28.9]
 [ 77.3]
 [ 57.8]
 [ 69.6]
 [ 76. ]
 [ 36.9]
 [ 62.5]
 [ 79.9]
 [ 71.3]
 [ 85.4]
 [ 87.4]
 [ 90. ]
 [ 96.7]
 [ 91.9]
 [ 85.2]
 [ 97.1]
 [ 91.2]
 [ 54.4]
 

### Creating a model and getting details

In [26]:
model = LinearRegression()   # obj from LinearRegression

In [27]:
model.fit(x,y)   # Model fitting

LinearRegression()

In [28]:
model.intercept_   # c of y= mx+c , beta note

30.97867776261804

In [29]:
model.coef_    # m, beta 1

array([-0.12316272])

In [30]:
model.score(x,y)   # R square value, not good r---->0

0.14209474407780442

# b) Multiple Linear Regression

In [33]:
x = data1.iloc[:,:12].values   #Already two diamentional
y = data1.iloc[:,12].values

In [34]:
model = LinearRegression()

In [35]:
model.fit(x,y)

LinearRegression()

In [26]:
model.intercept_   # c of y= mx+c , beta note

36.891959796933406

In [27]:
model.coef_    # 12 coefficients must be for 12 x variables, b1 hat(^), b2^, b3^,....b12^

array([-1.13139078e-01,  4.70524578e-02,  4.03114536e-02, -1.73669994e+01,
        3.85049169e+00,  2.78375651e-03, -1.48537390e+00,  3.28311011e-01,
       -1.37558288e-02, -9.90958031e-01,  9.74145094e-03, -5.34157620e-01])

In [28]:
model.score(x,y)   # R square value good --->1

0.7355165089722999

In [29]:
x = data1.iloc[:,:12].values   # All rows, 0 to 11th indexes columns
y = data1.iloc[:,12].values   # All rows, 12th index column

## Validation set approach

###### Let split the data by size (0.2-->20%) for testing, then  unpack the arrays ---> [[trx] , [tsx] , [try] , [tsy]] 
Generaly we don't use the entire data set to train a model. For checking the model accuracy (How the model is good for the prediction) we devide  the data set into four part as trainning and testing, 80% for trainning and 20% for testing both x and y.

##### To hold randomly choosing of data set we use " random_state = 0 or 1 or... " and  we can see the data set by using "  x_train ", "y_train", ...

In [36]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [37]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [38]:
model.intercept_   # c of y= mx+c , beta note

38.42706211257681

In [39]:
model.coef_   # 12 coefficients must be for 12 x variables, b1 hat(^), b2^, b3^,....b12^

array([-1.25156811e-01,  4.48575121e-02,  2.01265385e-02, -1.62895522e+01,
        3.77366409e+00, -2.13185120e-03, -1.40611846e+00,  2.66835482e-01,
       -1.21692284e-02, -1.07660161e+00,  8.72533635e-03, -4.94425348e-01])

In [42]:
model.score(x_train, y_train)   # R square value

0.7690953567794605

### Accuracy checking by test data

In Machine Learning , Blackbox Machine Learning means we focus about this particular error not the internal activities, 
we try to minimize these errors. Ther are so many techniques. Data set is realy importsnt specisly in the supervised learning

In [43]:
y_predict = model.predict(x_test)
y_predict

array([24.80502192, 23.99207878, 27.41969853, 12.22521383, 21.54089609,
       19.30502294, 20.70506397, 21.495484  , 18.94490741, 19.79344825,
        4.75978975, 16.4343098 , 17.29081528,  5.64718895, 38.15388163,
       32.57410093, 22.70379646, 37.01957565, 31.05648795, 23.25919894,
       24.92104056, 24.99282993, 20.64411415, 30.56600209, 22.55400948,
       10.168633  , 17.70825917, 18.49796497, 35.77195417, 21.08709139,
       18.5413341 , 18.01931143, 20.03791552, 24.23016879, 29.34270932,
       17.14453905, 11.29301586, 22.46300599, 17.65919302, 15.69991479,
       26.46863641, 20.99738044, 22.2127374 , 15.78922293, 22.90368303,
       25.37354909, 20.366435  , 20.84948352, 10.27162372, 24.36650689,
       18.72120276, 17.3722084 , 24.74428345, 30.0915379 , 13.45683478,
       21.89909332, 20.77900494, 15.37903094, 13.76748828, 20.0599973 ,
       17.4889214 , 21.74283257, 33.13151667, 31.34567345, 17.8919454 ,
       32.84969957, 18.97445875, 20.02078883, 19.17996866, 23.05

In [44]:
MSE = mean_squared_error(y_predict, y_test)
print("MSE = " ,MSE)
RMSE = np.sqrt(MSE)
print("RMSE = ", RMSE)  #It is good and more acurare if RMSE---> 0

MSE =  34.212252547533325
RMSE =  5.849124083786676


### Prediction
let create set of x , one row

In [51]:
x1 = np.array([0.00632,18.0,2.31,0.538,6.575,65.4,4.186,1,296,15.3,396.5,4.53]).reshape(1,12)   #row metrix
x1_predict = model.predict(x1)
print("predicted \"medv\" value for x1 = ", x1_predict)

predicted "medv" value for x1 =  [30.71541424]


# Full code Simple Linear Regerssion

In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

data1 = pd.read_csv("Boston.csv")
print("Boston Data set : \n",data1.head())

x = data1.iloc[:,5].values.reshape(506,1)    
y = data1.iloc[:,12].values                 
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)
model = LinearRegression()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
MSE = mean_squared_error(y_predict, y_test)
RMSE = np.sqrt(MSE)
print("\nIntercept = ",model.intercept_)
print("\nCoef = ",model.coef_)
print("\nR Score value = ",model.score(x_train, y_train))
print("\ny predict : \n",y_predict)
print("\nMean Squared Error = ",MSE)
print("\nRoot Mean Squared Error = ",RMSE)

x_check = np.array([7.147]).reshape(1,1)
x_check_predict = model.predict(x_check)
print(f"\nPredicted \"medv\" for x_check({x_check}) = ",x_check_predict)

Boston Data set : 
       crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  

Intercept =  31.99027826324518

Coef =  [-0.13586519]

R Score value =  0.17085002205933963

y predict : 
 [29.65339708 18.40375975 19.43633516 18.94722049 24.69431782 24.3138953
 24.76225041 24.04216493 26.85457426 20.38739145 18.40375975 18.40375975
 18.89287441 18.40375975 18.64831708 30.63162641 23.19980078 27.35727545
 27.49314063 26.35187308 24.88452908 18.77059575 20.4145644

# Full code Multiple Linear Regression

In [5]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

data1 = pd.read_csv("C:\\Users\\Pathum\\Desktop\\Folder\\Course\\Artificial intelligence\\Python\\Boston.csv")
print("Boston Data set : \n",data1.head())

x = data1.iloc[:,:12].values   
y = data1.iloc[:,12].values                 
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)
model = LinearRegression()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
MSE = mean_squared_error(y_predict, y_test)
RMSE = np.sqrt(MSE)
print("\nIntercept = ",model.intercept_)
print("\nCoef = ",model.coef_)
print("\nR Score value = ",model.score(x_train, y_train))
print("\ny predict : \n",y_predict)
print("\nMean Squared Error = ",MSE)
print("\nRoot Mean Squared Error = ",RMSE)

x1 = np.array([0.00632,18.0,2.31,0.538,6.575,65.4,4.186,1,296,15.3,396.5,4.53]).reshape(1,12)
x1_predict = model.predict(x1)
print("\nx1 : ",x1)
print("\nPredicted \"medv\" value for x1 = ", x1_predict)

Boston Data set : 
       crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  

Intercept =  38.42706211257681

Coef =  [-1.25156811e-01  4.48575121e-02  2.01265385e-02 -1.62895522e+01
  3.77366409e+00 -2.13185120e-03 -1.40611846e+00  2.66835482e-01
 -1.21692284e-02 -1.07660161e+00  8.72533635e-03 -4.94425348e-01]

R Score value =  0.7690953567794605

y predict : 
 [24.80502192 23.99207878 27.41969853 12.22521383 21.54089609 19.30502294
 20.70506397 21.495484 