# ML - SL - Linear Regression Algorithm continue ...
# Cross-Validation Technique
##### Normaly we don't use this technique for model accuracy checking or model selcting, but this is use for difference approaches.
### * Randomly choose testing data set

In [5]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from sklearn.feature_selection import RFE
from sklearn.feature_selection import RFECV

In [6]:
data = pd.read_csv("Boston.csv")
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [7]:
x = data.iloc[:,:12].values
y = data.iloc[:,12].values

In [10]:
model = LinearRegression()

##### We can't get mean squared error directly, negative mean squared error is there. It give the minus value of mean_squared_error so put " - " 
##### Let creat 10 iterations then we may have 10 mean squared errror values

In [20]:
cross_vals = -cross_val_score(model, x, y, cv = 10, scoring = "neg_mean_squared_error")   # return MSE for each iteration   
# cv is an argument(how many iterations/parts)

# scoring="neg_mean_squared_error": This specifies that the scoring metric to be used is the negative mean squared error (neg-MSE). 
# In scikit-learn, MSE is multiplied by -1 because cross_val_score always tries to maximize the score. By negating the MSE, 
# lower errors correspond to higher scores.

print(cross_vals) # MSE values

[  9.17006701  14.76188969  11.78968809  34.93168849  26.8851826
  19.52818886  10.70555866 171.48795123  35.0922184   11.64765827]


In [23]:
RMSE = np.sqrt(cross_vals)   # Square root of above MSE of return byh each iteration of "cross_val_score" function
print(RMSE)

[ 3.02821185  3.84212047  3.43361152  5.91030359  5.18509234  4.41907104
  3.271935   13.09534082  5.92386853  3.41286658]


##### Final Result, Avarage of RMSES

In [24]:
avg_RMSE = np.mean(RMSE)
print(avg_RMSE)

5.152242174479882


# Feature Selection
This is a technique in Machine Learning specialy in Linear Regression

When we have very larger number of x variables, really we don't need entire x variables. There some x variables which is less impact to responce variable. We can select most needfull variables and then we can remove that unwanted variables. In Machine Learning we have defferent defferent ways to do that.

* Best subset selection

* Forword selction

* Backword slection

* Stepwise selection

thing is these are not supported to python only in R - Language.

* Regularization  (L1 Regularization/LASSO regression, L2 Regularization/Ridge regression  and hybrid version of these Elastic Net regression) this is available in python.

But we have another algorithm in python( not a standard way like above things) called 
* Recursive Feature Elimination (RFE) 

## Recursive Feature Elimination (RFE)
This is a feature selection technique commonly used in machine learning to select the most relevant features from a dataset. Its main purpose is to improve the performance of a model by removing irrelevant or redundant features.
* Selcting most suitable variables

In [98]:
data1 = pd.read_csv("Boston.csv")
data1.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

For RFE not need to convert into arrays

In [99]:
dfx = data.iloc[:,:12]   # data frames 12 columns
dfy = data.iloc[:,12]

In [100]:
model = LinearRegression()

In [101]:
rfe = RFE(estimator = model, n_features_to_select=5)
rfe

RFE(estimator=LinearRegression(), n_features_to_select=5)

### Let fit the model, RFE select most suitable 5 from dfx

In [102]:
recursive_elimination = rfe.fit(dfx,dfy)
recursive_elimination

RFE(estimator=LinearRegression(), n_features_to_select=5)

### Boolean Masking

In [103]:
a = np.array([10,20,30,40,50])
a[[True, True, False, False, True]] 

array([10, 20, 50])

### Details of above fitted model

In [104]:
print(recursive_elimination.n_features_)
print(recursive_elimination.support_)   # True for took columns as most suitable
print(recursive_elimination.ranking_)   # 1 for availble in fitted model(selected by RFE), 2 for next valuble column
print(dfx.columns[recursive_elimination.support_])   # True index will be selected

5
[False False False  True  True False  True False False  True False  True]
[3 5 4 1 1 8 1 2 6 1 7 1]
Index(['nox', 'rm', 'dis', 'ptratio', 'lstat'], dtype='object')


### Most suitable columns

In [105]:
dfx[dfx.columns[recursive_elimination.support_]]   #True, False ---> columns---> True columns
#dfx already have 12 column gettin subset from suitable colummns we give column neames to dfx

nox     rm     dis  ptratio  lstat
0    0.538  6.575  4.0900     15.3   4.98
1    0.469  6.421  4.9671     17.8   9.14
2    0.469  7.185  4.9671     17.8   4.03
3    0.458  6.998  6.0622     18.7   2.94
4    0.458  7.147  6.0622     18.7   5.33
..     ...    ...     ...      ...    ...
501  0.573  6.593  2.4786     21.0   9.67
502  0.573  6.120  2.2875     21.0   9.08
503  0.573  6.976  2.1675     21.0   5.64
504  0.573  6.794  2.3889     21.0   6.48
505  0.573  6.030  2.5050     21.0   7.88

[506 rows x 5 columns]

## Recursive Feature Elimination Cross-Validation Technique(RFECV)
* Select most suitable variables automatically

* Recursive Feature Elimination with Cross-Validation (RFECV) is a feature(column) selection method used to identify the most important features of a dataset by recursively removing less significant features and evaluating the performance of the model. This process continues until the optimal number of features is achieved, as determined by cross-validation. RFECV is particularly useful for improving model performance, reducing overfitting, and simplifying the model.


### Benefits of RFECV
* Improved Model Performance: By selecting only the most relevant features, the model can perform better on unseen data.
* Reduced Overfitting: Eliminating less important features can help reduce the complexity of the model and prevent overfitting.
* Model Interpretability: A smaller set of features makes the model easier to interpret and understand

##### Here we selected 5 feature we given but we don't know what is the best number of features, for that we use 
* Recursive Feature Elimination Cross-Validation techniques

It will give the cross-validation, it split data into several parts and in each case it will run for an each combination.

All posible combinations will be performing cross validation and find the best feature set which gives the minimum cross validation error

In [25]:
data = pd.read_csv("Boston.csv")
dfx = data.iloc[:,:12]
dfy = data.iloc[:,12]
model = LinearRegression()

In [27]:
rfecv = RFECV (estimator = model, min_features_to_select = 1, cv = 10)
 # Don't give features amount but give minimum sholud be slected, and give CV 

In [29]:
rfecv_model = rfecv.fit(dfx, dfy)

### Details of fitted model

rfecv_model.n_features_

In [30]:
rfecv_model.support_

array([False, False, False,  True,  True, False,  True, False, False,
        True, False,  True])

In [31]:
dfx.columns[rfecv_model.support_]

Index(['nox', 'rm', 'dis', 'ptratio', 'lstat'], dtype='object')

In [32]:
rfecv_model.ranking_

array([3, 5, 4, 1, 1, 8, 1, 2, 6, 1, 7, 1])

In [34]:
selected = dfx.columns[rfecv_model.support_]

In [35]:
dfx[selected]

nox     rm     dis  ptratio  lstat
0    0.538  6.575  4.0900     15.3   4.98
1    0.469  6.421  4.9671     17.8   9.14
2    0.469  7.185  4.9671     17.8   4.03
3    0.458  6.998  6.0622     18.7   2.94
4    0.458  7.147  6.0622     18.7   5.33
..     ...    ...     ...      ...    ...
501  0.573  6.593  2.4786     21.0   9.67
502  0.573  6.120  2.2875     21.0   9.08
503  0.573  6.976  2.1675     21.0   5.64
504  0.573  6.794  2.3889     21.0   6.48
505  0.573  6.030  2.5050     21.0   7.88

[506 rows x 5 columns]

### Now let do prediction

In [36]:
x = dfx[selected]
y = dfy
model = LinearRegression()
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
MSE = mean_squared_error(y_predict, y_test)
RMSE = np.sqrt(MSE)
print("Intercept = ",model.intercept_)
print("\nCoef = ",model.coef_)
print("\nR Score value = ",model.score(x_train, y_train))
print("\ny predict \n",y_predict)
print("\nMean Squared Error = ",MSE)
print("\nRoot Mean Squared Error = ",RMSE)

Intercept =  41.34997736169525

Coef =  [-18.89689931   3.98424856  -1.08470716  -1.1970072   -0.56289908]

R Score value =  0.7471798491799624

y predict 
 [27.87223495 23.38001818 27.15874485 12.41107217 23.15282997 19.64298162
 19.81601057 20.76736396 19.01094421 23.09697956 14.5113339  18.81051713
 16.18935876  4.9670585  40.11212658 32.96959284 22.22717066 37.4418057
 31.52524995 23.04166063 25.19736838 26.3860131  20.68419971 29.1233784
 22.81659793 11.49563732 17.67527223 19.39197419 37.38255562 21.59490846
 17.70688586 16.70285008 20.6972236  23.82301832 29.44610975 15.43352965
 11.13638584 21.73093447 19.2705345  14.72685063 27.55291592 21.01313743
 25.41931656 14.91054897 26.9191263  26.23071693 21.2370457  21.30561092
  8.88232163 24.99257046 21.45776891 16.96075717 24.28752889 31.59466108
 14.83057251 21.96095771 21.37967539 18.1685699  21.60270112 19.66439592
 19.11891558 21.89424828 33.02125166 31.32531573 17.60096438 33.4979045
 17.67721397 20.26544871 20.46527211 22.917

In [37]:
# Create the feature array with feature names
x1 = np.array([[0.538, 6.575, 4.186, 15.4, 4.53]])
feature_names = ['nox', 'rm', 'dis', 'ptratio', 'lstat']
x1_named = pd.DataFrame(x1, columns=feature_names)
print(x1_named,"\n")

# Perform the prediction
x1_predict = model.predict(x1_named)
print("Predicted \"medv\" value for x1 = ", x1_predict)

     nox     rm    dis  ptratio  lstat
0  0.538  6.575  4.186     15.4   4.53 

Predicted "medv" value for x1 =  [31.85545194]


# Full code

In [39]:
# Multiple Linear Regression with Recursive Featurre Elimination-Cross Validation with Train Test Split
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import RFE
from sklearn.feature_selection import RFECV

data = pd.read_csv("Boston.csv")
dfx = data.iloc[:,:12]
dfy = data.iloc[:,12]
model = LinearRegression()

rfe_new = RFECV(estimator = model, min_features_to_select = 1, cv = 10)
elm = rfe_new.fit(dfx, dfy)

selected = dfx.columns[elm.support_]
dfx[selected]

x = dfx[selected]
y = dfy
model = LinearRegression()
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
model.fit(x_train, y_train)

cv_scores = cross_val_score(model, x, y, cv=10)
mean_cv_score = np.mean(cv_scores)
print("Mean Cross-Validation Score: ", mean_cv_score,"\n")

y_predict = model.predict(x_test)
MSE = mean_squared_error(y_predict, y_test)
RMSE = np.sqrt(MSE)
print("Supported columns according to RFECV : ",dfx.columns[elm.support_])
print("\nIntercept = ",model.intercept_)
print("\nCoef = ",model.coef_)
print("\nR Score value = ",model.score(x_train, y_train))
print("\ny predict \n",y_predict)
print("\nMean Squared Error = ",MSE)
print("\nRoot Mean Squared Error = ",RMSE)

x1 = np.array([[0.538, 6.575, 4.186, 15.4, 4.53]])
feature_names = ['nox', 'rm', 'dis', 'ptratio', 'lstat']
x1_named = pd.DataFrame(x1, columns=feature_names)

x1_predict = model.predict(x1_named)
print("\nPredicted \"medv\" value for x1 = ", x1_predict)

Mean Cross-Validation Score:  0.23500888207210227 

Supported columns according to RFECV :  Index(['nox', 'rm', 'dis', 'ptratio', 'lstat'], dtype='object')

Intercept =  41.34997736169525

Coef =  [-18.89689931   3.98424856  -1.08470716  -1.1970072   -0.56289908]

R Score value =  0.7471798491799624

y predict 
 [27.87223495 23.38001818 27.15874485 12.41107217 23.15282997 19.64298162
 19.81601057 20.76736396 19.01094421 23.09697956 14.5113339  18.81051713
 16.18935876  4.9670585  40.11212658 32.96959284 22.22717066 37.4418057
 31.52524995 23.04166063 25.19736838 26.3860131  20.68419971 29.1233784
 22.81659793 11.49563732 17.67527223 19.39197419 37.38255562 21.59490846
 17.70688586 16.70285008 20.6972236  23.82301832 29.44610975 15.43352965
 11.13638584 21.73093447 19.2705345  14.72685063 27.55291592 21.01313743
 25.41931656 14.91054897 26.9191263  26.23071693 21.2370457  21.30561092
  8.88232163 24.99257046 21.45776891 16.96075717 24.28752889 31.59466108
 14.83057251 21.96095771 21.379